### ISSUE TITLE
Missing index in the example

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/domain-information-library#1]
In this example file https://github.com/netgroup-polito/domain-information-library/blob/master/data_model/di_data.json, if I understood correctly the formalism, it is missing the `index` field inside the `interface` https://github.com/netgroup-polito/domain-information-library/blob/master/data_model/di_data.json#L7

**Comment by farmanullahcs** [comment]
Issue solve with commit [465f76f](https://github.com/netgroup-polito/domain-information-library/commit/465f76f391e1b562ae66ca7db77bca189988d75b)
